import { useEffect, useMemo, useState } from 'react';
import { Minus, Plus, Search, ShoppingCart, Trash2 } from 'lucide-react';
import { operationsApi, type Product } from '@/services/operations';
import { posApi, type PosSale } from '@/services/pos';
const money = (value: number) => new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN'}).format(value);
type CartLine = Product & { quantity: number; discount: number };
export function PosPage() {
  const [products,setProducts]=useState<Product[]>([]), [cart,setCart]=useState<CartLine[]>([]), [search,setSearch]=useState(''), [method,setMethod]=useState('CASH'), [received,setReceived]=useState(''), [busy,setBusy]=useState(false), [error,setError]=useState(''), [sale,setSale]=useState<PosSale|null>(null);
  useEffect(()=>{ void operationsApi.products({status:'active'}).then((items)=>setProducts(items.filter(x=>x.isActive))).catch(e=>setError(e instanceof Error?e.message:'Unable to load products')); },[]);
  const visible=useMemo(()=>products.filter(x=>`${x.name} ${x.sku} ${x.category||''}`.toLowerCase().includes(search.toLowerCase())).slice(0,24),[products,search]);
  const subtotal=cart.reduce((s,x)=>s+Number(x.salePrice)*x.quantity,0), discount=cart.reduce((s,x)=>s+x.discount,0), tax=cart.reduce((s,x)=>(s+(Number(x.salePrice)*x.quantity-x.discount)*Number(x.taxRate)/100),0), total=subtotal-discount+tax, paid=Number(received||0), change=Math.max(0,paid-total);
  const add=(p:Product)=>setCart(lines=>{const found=lines.find(x=>x.id===p.id);return found?lines.map(x=>x.id===p.id?{...x,quantity:x.quantity+1}:x):[...lines,{...p,quantity:1,discount:0}]});
  const complete=async()=>{setError('');if(!cart.length)return setError('Add an item to the sale.');if(method==='CASH'&&paid<total)return setError('Amount received is less than total due.');setBusy(true);try{const result=await posApi.complete({items:cart.map(x=>({productId:x.id,quantity:x.quantity,discount:x.discount})),payments:[{method,amount:method==='CASH'?paid:total}]});setSale(result);setCart([]);setReceived('');}catch(e){setError(e instanceof Error?e.message:'Unable to complete sale');}finally{setBusy(false)}};
  return <div className="pos-layout"><section className="panel pos-catalog"><label className="pos-search"><Search size={18}/><input placeholder="Scan barcode or search product" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="pos-products">{visible.map(p=><button key={p.id} onClick={()=>add(p)}><strong>{p.name}</strong><small>{p.sku}</small><b>{money(Number(p.salePrice))}</b></button>)}</div></section><section className="panel pos-cart"><header><h2><ShoppingCart size={18}/> New sale</h2><button onClick={()=>setCart([])}>Clear</button></header>{cart.map(line=><div className="pos-cart-lines" key={line.id}><span>{line.name}</span><button onClick={()=>setCart(c=>c.map(x=>x.id===line.id?{...x,quantity:Math.max(1,x.quantity-1)}:x))}><Minus size={13}/></button><b>{line.quantity}</b><button onClick={()=>setCart(c=>c.map(x=>x.id===line.id?{...x,quantity:x.quantity+1}:x))}><Plus size={13}/></button><b>{money(Number(line.salePrice)*line.quantity)}</b><button onClick={()=>setCart(c=>c.filter(x=>x.id!==line.id))}><Trash2 size={14}/></button></div>)}<div className="pos-summary"><span>Subtotal <b>{money(subtotal)}</b></span><span>Tax <b>{money(tax)}</b></span><strong>Total <b>{money(total)}</b></strong></div><div className="pos-payment"><select value={method} onChange={e=>setMethod(e.target.value)}><option value="CASH">Cash</option><option value="CARD">POS / Card</option><option value="TRANSFER">Bank transfer</option></select>{method==='CASH'&&<input type="number" placeholder="Amount received" value={received} onChange={e=>setReceived(e.target.value)}/>}<small>Change: {money(change)}</small></div>{error&&<p className="form-error">{error}</p>}<button className="button pos-pay" onClick={()=>void complete()} disabled={busy}>{busy?'Completing…':`Pay ${money(total)}`}</button>{sale&&<div className="pos-receipt"><strong>Sale completed: {sale.receiptNumber}</strong><span>Change: {money(Number(sale.changeAmount))}</span><button onClick={()=>setSale(null)}>New sale</button></div>}</section></div>;
}

